[package]
name = "notcurses"
version = "2.0.0"
authors = ["José Luis Cruz <joseluis@andamira.net>", "nick black <dankamongmen@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A higher level wrapper for the notcurses C library"
repository = "https://github.com/dankamongmen/notcurses-rs"
homepage = "https://nick-black.com/dankwiki/index.php/Notcurses"
readme = "./README.md"
edition = "2018"
categories = [
	"api-bindings",
	"command-line-interface",
	"visualization",
	"multimedia",
	"rendering",
	]
keywords = ["tui", "cli", "terminal", "ncurses"]
include = ["src/", "LICENSE-*", "README.md", "examples/"]

[dependencies]
libnotcurses-sys = { path="_deps/notcurses/rust/" } # WIP
# libnotcurses-sys = "3"
bitflags = "1.2.1"

# for the examples
plotters = { version = "^0.3", optional = true }
systemstat = { version = "^0.1", optional = true }


[dev-dependencies]
rand = "^0.8"
project-root = "^0.2"


[[example]]
name = "plotters-3d"
required-features = ["plotters"]

[[example]]
name = "plotters-cpustat"
required-features = ["plotters", "systemstat"]
