[package]
name = "notcurses"
version = "3.0.0-dev"
edition = "2021"
rust-version = "1.58.1"
authors = ["José Luis Cruz <joseluis@andamira.net>", "nick black <dankamongmen@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A high level Rust wrapper for the notcurses C library"
repository = "https://github.com/dankamongmen/notcurses-rs"
homepage = "https://nick-black.com/dankwiki/index.php/Notcurses"
readme = "./README.md"
categories = [
	"api-bindings",
	"command-line-interface",
	"visualization",
	"rendering",
	]
keywords = ["tui", "cli", "terminal", "ncurses"]
include = [
	"src/**/*rs",
	"Cargo.toml",
	"LICENSE-*",
	"README.md",
]
publish = false # TEMP

[dependencies]
az = "1.2.0"
# libnotcurses-sys = "3.5.0"
libnotcurses-sys = { path = "../libnotcurses-sys" }
once_cell = "1.10.0"
paste = "1.0.7"

[dev-dependencies]
rand = "0.8"

[badges]
maintenance = { status = "actively-developed" }
