[package]
name = "notcurses"
version = "2.0.0-alpha.1"
authors = ["José Luis Cruz <joseluis@andamira.net>", "nick black <dankamongmen@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "A safe and ergonomic wrapper for the notcurses C library"
repository = "https://github.com/dankamongmen/notcurses-rs"
homepage = "https://nick-black.com/dankwiki/index.php/Notcurses"
edition = "2018"
categories = [
	"api-bindings",
	"command-line-interface",
	"visualization",
	"multimedia",
	"rendering",
	]
keywords = ["tui", "cli", "terminal", "ncurses"]
include = ["src/", "LICENSE-*", "README.md"]

[dependencies]
#libnotcurses-sys = "^1.7" # ← waiting for the upcoming release
libnotcurses-sys = {git="https://github.com/dankamongmen/notcurses"}
#libnotcurses-sys = {path="../notcurses/rust/libnotcurses-sys/"}

libc = "^0.2.66"

thiserror = "^1.0.20"
strum = "^0.19"
strum_macros = "^0.19"

# using master version until next release. See:
# - https://github.com/NieDzejkob/enumflags2/issues/30
# - https://docs.rs/enumflags2/0.6.4/enumflags2/#optional-feature-flags
# enumflags2 = {version="0.6.4", features=["not_literal"]}
enumflags2 = {git="https://github.com/NieDzejkob/enumflags2/"}
