[alias]

# BUILD
b = "build"
br = "build --release"
bq = "build --quiet"

# CHECK
cl = "clippy"

# RUN
r = "run"
rr = "run --release"
rq = "run --quiet"
re = "run --example"
rqe = "run --quiet --example"
req = "rqe"

# DOC
d = "doc"
do = "doc --open"
# d = "doc --no-deps"
# do = "doc --no-deps --open"

# TEST
# fix IO errors: https://github.com/dankamongmen/notcurses/issues/766
t = "test -- --test-threads 1 --nocapture"
t_all = "test --no-fail-fast -- --test-threads 1 --nocapture"
